{% set name = "compas_ifc" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f66a0f29a8f51b16ae07a4d9253a5bc0710db639cde0cbeb0f49249622304fc5

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - compas >=2.2
    - ifcopenshell ==0.7.0.240406
    - lark

test:
  imports:
    - compas_ifc

about:
  home: https://compas.dev/compas_ifc/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'High-level IFC interface for COMPAS.'
  doc_url: https://compas.dev/compas_ifc/
  dev_url: https://github.com/compas-dev/compas_ifc

extra:
  recipe-maintainers:
    - tomvanmele
    - Licini
